function [ out ] = loadBinary(fname, type, sz)
% Purpose: read a file generated by Fortran and do reshape according to
% dimensions sz
% Usage: v = loadBinary('v.bin', 'float64', [zSz, kSz]);
% Note: float64 is the same as double
fileid = fopen(fname, 'rb');
out = fread(fileid, [prod(sz), 1], type);
fclose(fileid);
out = reshape(out, sz);

end %end function